<?php

namespace Webkul\TimeOff\Filament\Resources;

use Filament\Notifications\Notification;
use Filament\Support\Colors\Color;
use Filament\Support\Enums\FontWeight;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Collection;
use Webkul\Employee\Filament\Resources\EmployeeResource as BaseEmployeeResource;
use Webkul\Employee\Models\Employee;

class EmployeeResource extends BaseEmployeeResource
{
    protected static ?string $model = Employee::class;

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\Layout\Stack::make([
                    Tables\Columns\ImageColumn::make('partner.avatar')
                        ->height(150)
                        ->width(200),
                    Tables\Columns\Layout\Stack::make([
                        Tables\Columns\TextColumn::make('name')
                            ->label(__('employees::filament/resources/employee.table.columns.name'))
                            ->weight(FontWeight::Bold)
                            ->searchable()
                            ->sortable(),
                        Tables\Columns\Layout\Stack::make([
                            Tables\Columns\TextColumn::make('job_title')
                                ->icon('heroicon-m-briefcase')
                                ->searchable()
                                ->sortable()
                                ->label(__('employees::filament/resources/employee.table.columns.job-title')),
                        ])
                            ->visible(fn ($record) => filled($record->job_title)),
                        Tables\Columns\Layout\Stack::make([
                            Tables\Columns\TextColumn::make('work_email')
                                ->icon('heroicon-o-envelope')
                                ->searchable()
                                ->sortable()
                                ->label(__('employees::filament/resources/employee.table.columns.work-email'))
                                ->color('gray')
                                ->limit(20),
                        ])
                            ->visible(fn ($record) => filled($record->work_email)),
                        Tables\Columns\Layout\Stack::make([
                            Tables\Columns\TextColumn::make('work_phone')
                                ->icon('heroicon-o-phone')
                                ->searchable()
                                ->label(__('employees::filament/resources/employee.table.columns.work-phone'))
                                ->color('gray')
                                ->limit(30)
                                ->sortable(),
                        ])
                            ->visible(fn ($record) => filled($record->work_phone)),
                        Tables\Columns\Layout\Stack::make([
                            Tables\Columns\TextColumn::make('categories.name')
                                ->label(__('employees::filament/resources/employee.table.columns.categories'))
                                ->badge()
                                ->state(function (Employee $record): array {
                                    return $record->categories->map(fn ($category) => [
                                        'label' => $category->name,
                                        'color' => $category->color ?? '#808080',
                                    ])->toArray();
                                })
                                ->formatStateUsing(fn ($state) => $state['label'])
                                ->color(fn ($state) => Color::hex($state['color']))
                                ->weight(FontWeight::Bold),
                        ])
                            ->visible(fn ($record): bool => (bool) $record->categories()->get()?->count()),
                    ])->space(1),
                ])->space(4),
            ])
            ->contentGrid([
                'md' => 2,
                'xl' => 4,
            ])
            ->paginated([
                18,
                36,
                72,
                'all',
            ])
            ->filtersFormColumns(3)
            ->filters([
                Tables\Filters\SelectFilter::make('skills')
                    ->relationship('skills.skill', 'name')
                    ->searchable()
                    ->multiple()
                    ->label(__('employees::filament/resources/employee.table.filters.skills'))
                    ->preload(),
                Tables\Filters\SelectFilter::make('resumes')
                    ->relationship('resumes', 'name')
                    ->searchable()
                    ->label(__('employees::filament/resources/employee.table.filters.resumes'))
                    ->multiple()
                    ->preload(),
                Tables\Filters\SelectFilter::make('time_zone')
                    ->options(function () {
                        return collect(timezone_identifiers_list())->mapWithKeys(function ($timezone) {
                            return [$timezone => $timezone];
                        });
                    })
                    ->searchable()
                    ->label(__('employees::filament/resources/employee.table.filters.timezone'))
                    ->multiple()
                    ->preload(),
                Tables\Filters\QueryBuilder::make()
                    ->constraintPickerColumns(5)
                    ->constraints([
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('job_title')
                            ->label(__('employees::filament/resources/employee.table.filters.job-title'))
                            ->icon('heroicon-o-user-circle'),
                        Tables\Filters\QueryBuilder\Constraints\DateConstraint::make('birthday')
                            ->label(__('employees::filament/resources/employee.table.filters.birthdate'))
                            ->icon('heroicon-o-cake'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('work_email')
                            ->label(__('employees::filament/resources/employee.table.filters.work-email'))
                            ->icon('heroicon-o-at-symbol'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('mobile_phone')
                            ->label(__('employees::filament/resources/employee.table.filters.mobile-phone'))
                            ->icon('heroicon-o-phone'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('work_phone')
                            ->label(__('employees::filament/resources/employee.table.filters.work-phone'))
                            ->icon('heroicon-o-phone'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('is_flexible')
                            ->label(__('employees::filament/resources/employee.table.filters.is-flexible'))
                            ->icon('heroicon-o-cube'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('is_fully_flexible')
                            ->label(__('employees::filament/resources/employee.table.filters.is-fully-flexible'))
                            ->icon('heroicon-o-cube'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('is_active')
                            ->label(__('employees::filament/resources/employee.table.filters.is-active'))
                            ->icon('heroicon-o-cube'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('work_permit_scheduled_activity')
                            ->label(__('employees::filament/resources/employee.table.filters.work-permit-scheduled-activity'))
                            ->icon('heroicon-o-cube'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('emergency_contact')
                            ->label(__('employees::filament/resources/employee.table.filters.emergency-contact'))
                            ->icon('heroicon-o-phone'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('emergency_phone')
                            ->label(__('employees::filament/resources/employee.table.filters.emergency-phone'))
                            ->icon('heroicon-o-phone'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('private_phone')
                            ->label(__('employees::filament/resources/employee.table.filters.private-phone'))
                            ->icon('heroicon-o-phone'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('private_email')
                            ->label(__('employees::filament/resources/employee.table.filters.private-email'))
                            ->icon('heroicon-o-at-symbol'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('private_car_plate')
                            ->label(__('employees::filament/resources/employee.table.filters.private-car-plate'))
                            ->icon('heroicon-o-clipboard-document'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('distance_home_work')
                            ->label(__('employees::filament/resources/employee.table.filters.distance-home-work'))
                            ->icon('heroicon-o-map'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('km_home_work')
                            ->label(__('employees::filament/resources/employee.table.filters.km-home-work'))
                            ->icon('heroicon-o-map'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('distance_home_work_unit')
                            ->label(__('employees::filament/resources/employee.table.filters.distance-home-work-unit'))
                            ->icon('heroicon-o-map'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('marital')
                            ->label(__('employees::filament/resources/employee.table.filters.marital-status'))
                            ->icon('heroicon-o-user'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('spouse_complete_name')
                            ->label(__('employees::filament/resources/employee.table.filters.spouse-name'))
                            ->icon('heroicon-o-user'),
                        Tables\Filters\QueryBuilder\Constraints\DateConstraint::make('spouse_birthdate')
                            ->label(__('employees::filament/resources/employee.table.filters.spouse-birthdate'))
                            ->icon('heroicon-o-cake'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('certificate')
                            ->label(__('employees::filament/resources/employee.table.filters.certificate'))
                            ->icon('heroicon-o-document'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('study_field')
                            ->label(__('employees::filament/resources/employee.table.filters.study-field'))
                            ->icon('heroicon-o-academic-cap'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('study_school')
                            ->label(__('employees::filament/resources/employee.table.filters.study-school'))
                            ->icon('heroicon-o-academic-cap'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('identification_id')
                            ->label(__('employees::filament/resources/employee.table.filters.identification-id'))
                            ->icon('heroicon-o-credit-card'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('ssnid')
                            ->label(__('employees::filament/resources/employee.table.filters.ssnid'))
                            ->icon('heroicon-o-credit-card'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('sinid')
                            ->label(__('employees::filament/resources/employee.table.filters.sinid'))
                            ->icon('heroicon-o-credit-card'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('passport_id')
                            ->label(__('employees::filament/resources/employee.table.filters.passport-id'))
                            ->icon('heroicon-o-credit-card'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('gender')
                            ->label(__('employees::filament/resources/employee.table.filters.gender'))
                            ->icon('heroicon-o-user'),
                        Tables\Filters\QueryBuilder\Constraints\NumberConstraint::make('children')
                            ->label(__('employees::filament/resources/employee.table.filters.children'))
                            ->icon('heroicon-o-user'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('visa_no')
                            ->label(__('employees::filament/resources/employee.table.filters.visa-no'))
                            ->icon('heroicon-o-credit-card'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('permit_no')
                            ->label(__('employees::filament/resources/employee.table.filters.permit-no'))
                            ->icon('heroicon-o-credit-card'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('lang')
                            ->label(__('employees::filament/resources/employee.table.filters.language'))
                            ->icon('heroicon-o-language'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('additional_note')
                            ->label(__('employees::filament/resources/employee.table.filters.additional-note'))
                            ->icon('heroicon-o-language'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('notes')
                            ->label(__('employees::filament/resources/employee.table.filters.notes'))
                            ->icon('heroicon-o-language'),
                        Tables\Filters\QueryBuilder\Constraints\TextConstraint::make('barcode')
                            ->label(__('employees::filament/resources/employee.table.filters.barcode'))
                            ->icon('heroicon-o-qr-code'),
                        Tables\Filters\QueryBuilder\Constraints\DateConstraint::make('visa_expire')
                            ->label(__('employees::filament/resources/employee.table.filters.visa-expire'))
                            ->icon('heroicon-o-credit-card'),
                        Tables\Filters\QueryBuilder\Constraints\DateConstraint::make('work_permit_expiration_date')
                            ->label(__('employees::filament/resources/employee.table.filters.work-permit-expiration-date'))
                            ->icon('heroicon-o-calendar'),
                        Tables\Filters\QueryBuilder\Constraints\DateConstraint::make('departure_date')
                            ->label(__('employees::filament/resources/employee.table.filters.departure-date'))
                            ->icon('heroicon-o-calendar'),
                        Tables\Filters\QueryBuilder\Constraints\DateConstraint::make('departure_description')
                            ->label(__('employees::filament/resources/employee.table.filters.departure-description'))
                            ->icon('heroicon-o-cube'),
                        Tables\Filters\QueryBuilder\Constraints\DateConstraint::make('created_at')
                            ->label(__('employees::filament/resources/employee.table.filters.created-at')),
                        Tables\Filters\QueryBuilder\Constraints\DateConstraint::make('updated_at')
                            ->label(__('employees::filament/resources/employee.table.filters.updated-at')),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('company')
                            ->label(__('employees::filament/resources/employee.table.filters.company'))
                            ->icon('heroicon-o-building-office-2')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('creator')
                            ->label(__('employees::filament/resources/employee.table.filters.created-by'))
                            ->icon('heroicon-o-user')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('calendar')
                            ->label(__('employees::filament/resources/employee.table.filters.calendar'))
                            ->icon('heroicon-o-calendar')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('department')
                            ->label(__('employees::filament/resources/employee.table.filters.department'))
                            ->multiple()
                            ->icon('heroicon-o-building-office-2')
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('job')
                            ->label(__('employees::filament/resources/employee.table.filters.job'))
                            ->icon('heroicon-o-briefcase')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('partner')
                            ->label(__('employees::filament/resources/employee.table.filters.partner'))
                            ->icon('heroicon-o-user-group')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('leaveManager')
                            ->label(__('employees::filament/resources/employee.table.filters.leave-approvers'))
                            ->icon('heroicon-o-user-group')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('attendanceManager')
                            ->label(__('employees::filament/resources/employee.table.filters.attendance'))
                            ->icon('heroicon-o-user-group')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('workLocation')
                            ->label(__('employees::filament/resources/employee.table.filters.work-location'))
                            ->multiple()
                            ->icon('heroicon-o-map-pin')
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('parent')
                            ->label(__('employees::filament/resources/employee.table.filters.manager'))
                            ->icon('heroicon-o-user')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('coach')
                            ->label(__('employees::filament/resources/employee.table.filters.coach'))
                            ->multiple()
                            ->icon('heroicon-o-user')
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('privateState')
                            ->label(__('employees::filament/resources/employee.table.filters.private-state'))
                            ->multiple()
                            ->icon('heroicon-o-map-pin')
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('privateCountry')
                            ->label(__('employees::filament/resources/employee.table.filters.private-country'))
                            ->icon('heroicon-o-map-pin')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('country')
                            ->label(__('employees::filament/resources/employee.table.filters.country'))
                            ->icon('heroicon-o-map-pin')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('state')
                            ->label(__('employees::filament/resources/employee.table.filters.state'))
                            ->icon('heroicon-o-map-pin')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('countryOfBirth')
                            ->label(__('employees::filament/resources/employee.table.filters.country-of-birth'))
                            ->multiple()
                            ->icon('heroicon-o-calendar')
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('bankAccount')
                            ->label(__('employees::filament/resources/employee.table.filters.bank-account'))
                            ->multiple()
                            ->icon('heroicon-o-banknotes')
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('account_holder_name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('departureReason')
                            ->label(__('employees::filament/resources/employee.table.filters.departure-reason'))
                            ->icon('heroicon-o-fire')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('employmentType')
                            ->label(__('employees::filament/resources/employee.table.filters.employee-type'))
                            ->multiple()
                            ->icon('heroicon-o-academic-cap')
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                        Tables\Filters\QueryBuilder\Constraints\RelationshipConstraint::make('categories')
                            ->label(__('employees::filament/resources/employee.table.filters.tags'))
                            ->icon('heroicon-o-tag')
                            ->multiple()
                            ->selectable(
                                IsRelatedToOperator::make()
                                    ->titleAttribute('name')
                                    ->searchable()
                                    ->multiple()
                                    ->preload(),
                            ),
                    ]),
            ])
            ->groups([
                Tables\Grouping\Group::make('name')
                    ->label(__('employees::filament/resources/employee.table.groups.name'))
                    ->collapsible(),
                Tables\Grouping\Group::make('company.name')
                    ->label(__('employees::filament/resources/employee.table.groups.company'))
                    ->collapsible(),
                Tables\Grouping\Group::make('parent.name')
                    ->label(__('employees::filament/resources/employee.table.groups.manager'))
                    ->collapsible(),
                Tables\Grouping\Group::make('coach.name')
                    ->label(__('employees::filament/resources/employee.table.groups.coach'))
                    ->collapsible(),
                Tables\Grouping\Group::make('department.complete_name')
                    ->label(__('employees::filament/resources/employee.table.groups.department'))
                    ->collapsible(),
                Tables\Grouping\Group::make('employmentType.name')
                    ->label(__('employees::filament/resources/employee.table.groups.employment-type'))
                    ->collapsible(),
                Tables\Grouping\Group::make('categories.name')
                    ->label(__('employees::filament/resources/employee.table.groups.tags'))
                    ->collapsible(),
                Tables\Grouping\Group::make('departureReason.name')
                    ->label(__('employees::filament/resources/employee.table.groups.departure-reason'))
                    ->collapsible(),
                Tables\Grouping\Group::make('privateState.name')
                    ->label(__('employees::filament/resources/employee.table.groups.private-state'))
                    ->collapsible(),
                Tables\Grouping\Group::make('privateCountry.name')
                    ->label(__('employees::filament/resources/employee.table.groups.private-country'))
                    ->collapsible(),
                Tables\Grouping\Group::make('country.name')
                    ->label(__('employees::filament/resources/employee.table.groups.country'))
                    ->collapsible(),
                Tables\Grouping\Group::make('state.name')
                    ->label(__('employees::filament/resources/employee.table.groups.state'))
                    ->collapsible(),
                Tables\Grouping\Group::make('created_at')
                    ->label(__('employees::filament/resources/employee.table.groups.created-at'))
                    ->date()
                    ->collapsible(),
                Tables\Grouping\Group::make('updated_at')
                    ->label(__('employees::filament/resources/employee.table.groups.updated-at'))
                    ->date()
                    ->collapsible(),
            ])
            ->defaultSort('name')
            ->persistSortInSession()
            ->actions([
                Tables\Actions\ViewAction::make()
                    ->outlined(),
                Tables\Actions\EditAction::make()
                    ->outlined(),
                Tables\Actions\RestoreAction::make()
                    ->outlined()
                    ->successNotification(
                        Notification::make()
                            ->success()
                            ->title(__('employees::filament/resources/employee.table.actions.restore.notification.title'))
                            ->body(__('employees::filament/resources/employee.table.actions.restore.notification.body'))
                    ),
                Tables\Actions\DeleteAction::make()
                    ->successNotification(
                        Notification::make()
                            ->success()
                            ->title(__('employees::filament/resources/employee.table.actions.delete.notification.title'))
                            ->body(__('employees::filament/resources/employee.table.actions.delete.notification.body'))
                    ),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make()
                        ->successNotification(
                            Notification::make()
                                ->success()
                                ->title(__('employees::filament/resources/employee.table.bulk-actions.delete.notification.title'))
                                ->body(__('employees::filament/resources/employee.table.bulk-actions.delete.notification.body'))
                        ),
                    Tables\Actions\ForceDeleteBulkAction::make()
                        ->before(function (Collection $records) {
                            foreach ($records as $record) {
                                $record?->timeOffLeaves()?->delete();
                            }
                        })
                        ->successNotification(
                            Notification::make()
                                ->success()
                                ->title(__('employees::filament/resources/employee.table.bulk-actions.force-delete.notification.title'))
                                ->body(__('employees::filament/resources/employee.table.bulk-actions.force-delete.notification.body'))
                        ),
                ]),
            ]);
    }
}
